<?php

/**
 * @file
 * Display My Courses.
 */

/**
 * Implements hook_init().
 */

function angular_test_menu() {
  $items = array();

  $items['my_angular'] = array(
    'title' => 'Basic Angular.js in a Drupal7 fetching json restfully',
    'description' => 'My Angular, basic Angular.js in a Drupal7 Environment!!!!!',
    'page callback' => 'angular_test_page',
    'access arguments' => array('access content'),
    'weight' => 30,
  );
return $items;
}

function angular_test_page() {
  drupal_add_js(drupal_get_path('module', 'angular_test') . '/js/angular_test.js', array(
    'scope' => 'footer'));
  $output =  array(
    'first_para' => array(
      '#type' => 'markup',
      '#markup' => '

<div ng-app="myApp" ng-controller="MainCtrl">
    <h2>My Todo List</h2>
    <button ng-hide="buttonClicked" ng-click="fetchTodoListItems()" type="button">Click Me to restore your Todo List restfully from a json file!</button>
    <button ng-if="buttonClicked" ng-click="cancelTodoListItems()" type="button">Cancel</button>

    <form ng-submit="todoAdd()">
      <input type="text" ng-model="todoInput" size="50" placeholder="Add New">
      <input type="submit" value="Add New">
      
      <br>

      <div ng-repeat="x in todoList">
        <input type="checkbox" ng-model="x.done"> <input type="text" ng-model=x.todoText value={{x.todoText}}>
      </div>

      <p><button ng-click="remove()">Remove marked</button></p>

    </form>',
      '#attached' => array(
        'js' => array(
          'https://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.min.js',
          'https://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular-resource.js',
        ),
      ),
    )
  );
  return $output;

}
